# Generated by Django 5.1.1 on 2024-09-09 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Contact_Number', models.CharField(max_length=100, null=True)),
                ('Carrer_Summary', models.TextField(max_length=100, null=True)),
                ('Experience_Title', models.CharField(max_length=100, null=True)),
                ('Skill_Title', models.CharField(max_length=100, null=True)),
                ('Education_Title', models.CharField(max_length=100, null=True)),
                ('Language', models.CharField(max_length=100, null=True)),
                ('Interest', models.CharField(max_length=100, null=True)),
                ('Profile_pic', models.ImageField(null=True, upload_to='Media/Profile_Pic')),
                ('Linkedin_URL', models.URLField(null=True)),
                ('Facebook_URL', models.URLField(null=True)),
                ('Instagram_URL', models.URLField(null=True)),
                ('GitHub_URL', models.URLField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
