# Generated by Django 5.1.1 on 2024-09-18 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_languagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='Proficiency_Level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='IntermediateLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_Name', models.CharField(max_length=100, null=True)),
                ('All_Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.languagemodel')),
            ],
        ),
    ]
