# Generated by Django 5.1.1 on 2024-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_languagemodel_proficiency_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='user',
            new_name='myLanguage',
        ),
        migrations.RemoveField(
            model_name='intermediatelanguagemodel',
            name='All_Language',
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='Age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
