# Generated by Django 5.1.1 on 2024-09-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_user_languagemodel_mylanguage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='myLanguage',
            new_name='user',
        ),
    ]
