# Generated by Django 5.1.1 on 2024-09-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_language_model_experience_model_interest_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
