# Generated by Django 5.1.1 on 2024-09-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_mylanguage_languagemodel_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemodel',
            unique_together={('user', 'Language_Name')},
        ),
    ]
