# Generated by Django 5.1.1 on 2024-09-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_languagemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemodel',
            unique_together={('user', 'Language_Name')},
        ),
    ]
