# Generated by Django 5.0.6 on 2024-09-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0013_intermediateskillmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatelanguagemodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
