# Generated by Django 5.0.6 on 2024-09-22 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0015_intermediateeducationmodel_resumemodel_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediateeducationmodel",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="intermediateeducationmodel",
            name="start_date",
        ),
    ]
