# Generated by Django 5.0.6 on 2024-09-22 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0016_remove_intermediateeducationmodel_end_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IntermediateEducationModel",
        ),
    ]
