# Generated by Django 5.0.6 on 2024-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0018_institutename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstituteName",
            new_name="InstituteNameModel",
        ),
    ]
