# Generated by Django 5.0.6 on 2024-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0019_rename_institutename_institutenamemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
