# Generated by Django 5.0.6 on 2024-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0020_degreemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldOfStudyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
