# Generated by Django 5.0.6 on 2024-09-22 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0024_addjobmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResumeModel",
            new_name="BasicInfoModel",
        ),
    ]
