# Generated by Django 5.0.6 on 2024-09-22 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0025_rename_resumemodel_basicinfomodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addjobmodel",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="addjobmodel",
            name="job_description",
        ),
        migrations.RemoveField(
            model_name="addjobmodel",
            name="start_date",
        ),
        migrations.AddField(
            model_name="addjobmodel",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="addjobmodel",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addjobmodel",
            name="posted_on",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="addjobmodel",
            name="updated_on",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="addjobmodel",
            name="company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="addjobmodel",
            name="job_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
